app:
    resource: '@AppBundle/Controller/'
    type: annotation

index_page:
    path: /
    defaults:
        _controller: AppBundle:Default:index

blog_new:
    path: /blog/new
    defaults:
        _controller: AppBundle:Blog:new

blog_page:
    path: /blog/{blogId}
    defaults:
        _controller: AppBundle:Blog:index